name: CI

on:
  push:
    branches:
      - main
      - dev
      - SponsorBlockPatch
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'gradle/*.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Retrieve version
        run: |
          version=`awk -F "=" '$1 == "version" {print $2}' gradle.properties`
          commit_count=`git rev-list HEAD --count`
          version="${version}.r${commit_count}"
          echo "VERSION=$version" >> $GITHUB_ENV

      # try setup ssh
      - name: Set up SSH
        uses: sti-233/ssh-agent@master
        with:
           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build with gradle
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          rm ./integrations/app/src/main/java/app/revanced/bilibili/utils/KtUtils.kt
          rm ./integrations/app/src/main/java/app/revanced/bilibili/account/Accounts.kt
          rm ./integrations/app/src/main/java/app/revanced/bilibili/http/HttpClient.kt
          git clone git@github.com:sti-233/Close-BiliRoamingX.git
          mv ./Close-BiliRoamingX/KtUtils.kt ./integrations/app/src/main/java/app/revanced/bilibili/utils/KtUtils.kt
          mv ./Close-BiliRoamingX/Accounts.kt ./integrations/app/src/main/java/app/revanced/bilibili/account/Accounts.kt
          mv ./Close-BiliRoamingX/HttpClient.kt ./integrations/app/src/main/java/app/revanced/bilibili/http/HttpClient.kt
          ./gradlew --no-daemon -Dorg.gradle.jvmargs=-Xmx2g -Pversion=$VERSION dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: BiliRoamingX-${{ env.VERSION }}
          path: 'build'
