name: Update Gradle Wrapper

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Update gradle wrapper
        uses: zjns/update-gradle-wrapper-action@main
        with:
          repo-token: ${{ secrets.gh_token }}
          pr-title-template: 'build(deps): bump gradle wrapper from %sourceVersion% to %targetVersion%'
